build:
  image: golang:1.5.1
  environment:
    - GO15VENDOREXPERIMENT=1
  environment:
    - GOPATH=/drone-kubernetes
  commands:
    - go get github.com/drone/drone-go/drone
    - go get github.com/drone/drone-go/plugin
    - go get gopkg.in/yaml.v2
    - go get github.com/stretchr/testify/assert
    - go test
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo

publish:
  docker:
    registry: quay.io
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    username: $$QUAY_USER
    password: $$QUAY_PASSWORD
    email: $$QUAY_EMAIL
    repo: quay.io/ukhomeofficedigital/drone-kubernetes
    storage_driver: vfs
    tag:
      - latest
      - "$$BUILD_NUMBER"
    when:
      branch: master

    branch: master

